version: 2.1

executors:
  ruby_3_1:
    docker:
      - image: ruby:3.1

  ruby_3_2:
    docker:
      - image: ruby:3.2

  ruby_3_3:
    docker:
      - image: ruby:3.3

  ruby_3_4:
    docker:
      - image: ruby:3.4

jobs:
  run_test:
    parameters:
      executor:
        type: string
    executor: << parameters.executor >>
    resource_class: small
    steps:
      - checkout
      - run: command -v bundle &> /dev/null || gem install bundler
      - run: bundle install
      - run: bundle exec rspec
      - run: bundle exec rubocop

workflows:
  version: 2

  test:
    jobs:
      - run_test:
          matrix:
            parameters:
              executor:
                - ruby_3_1
                - ruby_3_2
                - ruby_3_3
                - ruby_3_4
